#https://hub.docker.com/r/wernight/mopidy/
mopidy:
  build: ../.
  dockerfile: DockerfileX86
  volumes:
    - ../mopidy.conf:/var/lib/mopidy/.config/mopidy/mopidy.conf
  expose: 
    - "6379"
  ports: 
    - "6600:6600"
    - "6680:6680" 
  command: "mopidy -v --config /var/lib/mopidy/.config/mopidy/mopidy.conf"    
  net: "host"
